name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # create and set it to patch or minor or major depending on the commit message
      - name: get bump type
        id: bump
        run: |
          echo "Bump type: bump minor"
          if [[ "bump minor" =~ .*"\[patch\]".* ]]; then
            echo "::set-output name=bump::patch"
          elif [[ "bump minor" =~ .*"\[minor\]".* ]]; then
            echo "::set-output name=bump::minor"
          elif [[ "bump minor" =~ .*"\[major\]".* ]]; then
            echo "::set-output name=bump::major"
          else
            echo "::set-output name=bump::patch"
          fi
        shell: /usr/bin/bash -e {0}
      # checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Upgrade pip & Install Poetry.
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependecies and bump version
        run: |
          poetry install
          poetry run bumpver --${{ steps.bump.outputs.bump }}
          cat pyproject.toml
