# This is a basic workflow to help you get started with the GitHub Auto-Release on Commit Action.

name: AutoRelease

on:
  workflow_dispatch


permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: install dependecies
        uses: ouhammmourachid/poetry-install@main
      - name: test
        run: poetry show --tree

