# This is a basic workflow to help you get started with the GitHub Auto-Release on Commit Action.

name: AutoRelease

on:
  workflow_dispatch


permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: checout
        uses: actions/checkout@v4
      - name: install dependecies
        uses: ouhammmourachid/poetry-install@v1
        with:
          python-version: "3.11"
      - name: test
        run: poetry run python --version

